# Add this to your existing docker-compose.yml or create docker-compose-tracing.yml

version: '3.8'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      - creditx-network

networks:
  creditx-network:
    external: true
