services:
  # Zipkin for distributed tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: unless-stopped

  # Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Oracle Database
  oracle-free:
    container_name: oracle-free
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: "AL32UTF8"
      ORACLE_PDB: FREEPDB1
      INIT_PWD: ${ORACLE_PWD}
      INIT_USER: ${ORACLE_USER}
      INIT_PASSWORD: ${ORACLE_PASSWORD}
    healthcheck:
      test: ["CMD",
          "bash",
          "-c",
          "sqlplus -S 'system/${ORACLE_PWD}@//localhost:1521/FREEPDB1' <<EOF\nSELECT 1 FROM DUAL;\nEXIT;\nEOF"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - creditx_oradata:/opt/oracle/oradata
    restart: unless-stopped

  # Main Service
  creditmainserv:
    container_name: creditx-main-serv
    build:
      context: ./creditMainServ
    image: creditx-creditmainserv
    ports:
      - "8080:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}_MAIN
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      CREDITHOLD_URL: ${CREDITHOLD_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      oracle-free:
        condition: service_healthy
      kafka:
        condition: service_healthy
      creditholdserv:
        condition: service_started

  # Hold Service
  creditholdserv:
    container_name: creditx-hold-serv
    build:
      context: ./creditHoldServ
    image: creditx-creditholdserv
    ports:
      - "8081:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}_HOLD
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      oracle-free:
        condition: service_healthy
      kafka:
        condition: service_healthy

  # Posting Service
  creditpostingserv:
    container_name: creditx-posting-serv
    build:
      context: ./creditPostingServ
    image: creditx-creditpostingserv
    ports:
      - "8082:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}_POST
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      CREDITMAIN_URL: ${CREDITMAIN_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      oracle-free:
        condition: service_healthy
      kafka:
        condition: service_healthy
      creditmainserv:
        condition: service_started

  # Promo Service
  creditpromoserv:
    container_name: creditx-promo-serv
    build:
      context: ./creditPromoServ
    image: creditx-creditpromoserv
    ports:
      - "8083:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}_PROMO
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      CREDITMAIN_URL: ${CREDITMAIN_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      oracle-free:
        condition: service_healthy
      kafka:
        condition: service_healthy
      creditmainserv:
        condition: service_started

volumes:
  creditx_oradata: