services:
  # Oracle Database
  oracle-free:
    container_name: oracle-free
    image: gvenzl/oracle-free:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: "AL32UTF8"
      ORACLE_PDB: FREEPDB1
    healthcheck:
      test: ["CMD",
          "bash",
          "-c",
          "sqlplus -S 'system/${ORACLE_PWD}@//localhost:1521/FREEPDB1' <<EOF\nSELECT 1 FROM DUAL;\nEXIT;\nEOF"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - creditx_oradata:/opt/oracle/oradata
    restart: unless-stopped

  # Main Service
  creditmainserv:
    container_name: creditx-main-serv
    build:
      context: ./creditMainServ
    image: creditx-creditmainserv
    ports:
      - "8080:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    depends_on:
      oracle-free:
        condition: service_healthy

  # Hold Service
  creditholdserv:
    container_name: creditx-hold-serv
    build:
      context: ./creditHoldServ
    image: creditx-creditholdserv
    ports:
      - "8081:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    depends_on:
      oracle-free:
        condition: service_healthy

  # Posting Service
  creditpostingserv:
    container_name: creditx-posting-serv
    build:
      context: ./creditPostingServ
    image: creditx-creditpostingserv
    ports:
      - "8082:8080"
    environment:
      ORACLE_HOST: oracle-free
      ORACLE_PORT: 1521
      ORACLE_SVC: FREEPDB1
      ORACLE_USER: ${ORACLE_USER}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    depends_on:
      oracle-free:
        condition: service_healthy

volumes:
  creditx_oradata: